name: my_docker_rails_project
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rails-docker
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.4.2

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
      - redis
    volumes:
      - .:/app
    env_file: .env
    entrypoint: ./sidekiq-entrypoint.sh

volumes:
    db_data:
