default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: docker_rails_development
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>
  host: <%= ENV['DBHOST'] %>

test:
  <<: *default
  database: docker_rails_test
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>
  host: <%= ENV['DBHOST'] %>


production:
  primary: &primary_production
    <<: *default
    database: docker_rails_production
    username: docker_rails
    password: <%= ENV["DOCKER_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: docker_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: docker_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: docker_rails_production_cable
    migrations_paths: db/cable_migrate
